- id: dfixxer
  name: dfixxer
  description: Format Delphi/Pascal source code with dfixxer
  entry: dfixxer-hook
  language: python
  files: '\.pas$'
  require_serial: false
  additional_dependencies: []